version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      docusaurus:
        patterns:
          - '@docusaurus/*'
      minor-and-patch:
        update-types:
          - minor
          - patch
        exclude-patterns:
          - '@docusaurus/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
