services:
  dev:
    image: node:18
    container_name: ose-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: sh -c "npm install && npm run develop"
    stdin_open: true
    tty: true

  prod:
    build: .
    container_name: ose-prod
    ports:
      - "8080:8080"

