services:
  dev:
    image: node:18-bullseye
    container_name: ose-dev
    working_dir: /app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "8000:8000"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    command: sh -c "npm install && npx gatsby develop -H 0.0.0.0"
    stdin_open: true
    tty: true

  prod:
    build: .
    container_name: ose-prod
    ports:
      - "8080:8080"

